### ISSUE TITLE
Clarifying README.md

### ISSUE THREAD

**Issue by BRousserie** [UnleavenedEagle/SimpleWrapperLauncher#3]
Thank you for the workaround !

I would only suggest to reformulate the sentence "Rename the original application with the name .exe to _.exe" in README.md. I didn't understand that the _ had to be at the beginning of the filename, and I had to read source.cs for it.
I'd suggest something like "Rename the original application by adding _ **at the beginning**", for example.

Thank you again ! I really enjoy your workaround, I only point this out as I think it could help other users to understand more easiely.

**Comment by UnleavenedEagle** [comment]
The plain text version of the markdown file had `<name>.exe` and `_<name>.exe` instead of `.exe` and `_.exe`, but it cut `<name>` from it. It would have made more sense if `<name>` was visible.

I have encased `<name>` with the backtick symbol as well as added a sentence you suggested for further clarification.
